<div>
    <table class="table">
        <tbody>
            <tr>
                <td></td>
                <td>5:00</td>
                <td>8:00</td>
                <td>11:00</td>
                <td>14:00</td>
                <td>17:00</td>
            </tr>
            <tr>
                <td>Četvrtak</td>
            </tr>
            <tr>
                <td>Petak</td>
            </tr>
        </tbody>
    </table>
</div>
